"""remove_contacts

Revision ID: 1053bbd6ffce
Revises: 988afb3577dc
Create Date: 2026-02-03 20:34:41.011249

"""

from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "1053bbd6ffce"
down_revision: Union[str, None] = "988afb3577dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
