"""add_user_tracking

Revision ID: 62d11d93a63c
Revises: b252ee9cd3c4
Create Date: 2026-02-03 22:44:54.863947

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62d11d93a63c"
down_revision: Union[str, None] = "b252ee9cd3c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotent migration: Only add columns if they don't exist
    # Production might have these columns already from manual migrations
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Helper function to check if column exists
    def column_exists(table_name, column_name):
        if table_name not in inspector.get_table_names():
            return False
        columns = [col["name"] for col in inspector.get_columns(table_name)]
        return column_name in columns

    # Add user_id to resident_care_logs
    if "resident_care_logs" in inspector.get_table_names() and not column_exists(
        "resident_care_logs", "user_id"
    ):
        op.add_column(
            "resident_care_logs",
            sa.Column("user_id", sa.Integer(), nullable=True),
        )
        op.create_index(
            op.f("ix_resident_care_logs_user_id"),
            "resident_care_logs",
            ["user_id"],
            unique=False,
        )
        op.create_foreign_key(
            None,
            "resident_care_logs",
            "users",
            ["user_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # Add user_id to resident_vaccinations
    if "resident_vaccinations" in inspector.get_table_names() and not column_exists(
        "resident_vaccinations", "user_id"
    ):
        op.add_column(
            "resident_vaccinations",
            sa.Column("user_id", sa.Integer(), nullable=True),
        )
        # ... logic for vaccines ...
        op.create_index(
            op.f("ix_resident_vaccinations_user_id"),
            "resident_vaccinations",
            ["user_id"],
            unique=False,
        )
        op.create_foreign_key(
            None,
            "resident_vaccinations",
            "users",
            ["user_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # Add user_id to resident_vitals
    if "resident_vitals" in inspector.get_table_names() and not column_exists(
        "resident_vitals", "user_id"
    ):
        op.add_column(
            "resident_vitals",
            sa.Column("user_id", sa.Integer(), nullable=True),
        )
        op.create_index(
            op.f("ix_resident_vitals_user_id"),
            "resident_vitals",
            ["user_id"],
            unique=False,
        )
        op.create_foreign_key(
            None,
            "resident_vitals",
            "users",
            ["user_id"],
            ["id"],
            ondelete="SET NULL",
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "resident_vitals", type_="foreignkey")
    op.drop_index(op.f("ix_resident_vitals_user_id"), table_name="resident_vitals")
    op.drop_column("resident_vitals", "user_id")
    op.drop_constraint(None, "resident_vaccinations", type_="foreignkey")
    op.drop_index(
        op.f("ix_resident_vaccinations_user_id"),
        table_name="resident_vaccinations",
    )
    op.drop_column("resident_vaccinations", "user_id")
    op.drop_constraint(None, "resident_care_logs", type_="foreignkey")
    op.drop_index(op.f("ix_resident_care_logs_user_id"), table_name="resident_care_logs")
    op.drop_column("resident_care_logs", "user_id")
    # ### end Alembic commands ###
