"""remove_documents

Revision ID: 988afb3577dc
Revises: a6c63a0920c3
Create Date: 2026-02-03 20:14:19.203868

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "988afb3577dc"
down_revision: Union[str, None] = "a6c63a0920c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotent migration: Only drop if exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if "resident_documents" in inspector.get_table_names():
        try:
            op.drop_index(
                op.f("ix_resident_documents_document_date"),
                table_name="resident_documents",
            )
        except Exception:
            pass
        try:
            op.drop_index(
                op.f("ix_resident_documents_document_type"),
                table_name="resident_documents",
            )
        except Exception:
            pass
        try:
            op.drop_index(
                op.f("ix_resident_documents_id"),
                table_name="resident_documents",
            )
        except Exception:
            pass
        try:
            op.drop_index(
                op.f("ix_resident_documents_resident_id"),
                table_name="resident_documents",
            )
        except Exception:
            pass
        op.drop_table("resident_documents")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resident_documents",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("resident_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("document_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("file_path", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("document_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("uploaded_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["resident_id"],
            ["residents.id"],
            name=op.f("resident_documents_resident_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("resident_documents_pkey")),
    )
    op.create_index(
        op.f("ix_resident_documents_resident_id"),
        "resident_documents",
        ["resident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resident_documents_id"),
        "resident_documents",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resident_documents_document_type"),
        "resident_documents",
        ["document_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resident_documents_document_date"),
        "resident_documents",
        ["document_date"],
        unique=False,
    )
    # ### end Alembic commands ###
