"""remove_therapy

Revision ID: a6c63a0920c3
Revises: 46bf0760714e
Create Date: 2026-02-03 20:08:06.672261

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a6c63a0920c3"
down_revision: Union[str, None] = "46bf0760714e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotent migration: Only drop if exists
    # Production might have already removed this table manually
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if "resident_therapies" in inspector.get_table_names():
        # Table exists, drop indexes first then table
        try:
            op.drop_index(
                op.f("ix_resident_therapies_active"),
                table_name="resident_therapies",
            )
        except Exception:
            pass  # Index might not exist
        try:
            op.drop_index(
                op.f("ix_resident_therapies_id"),
                table_name="resident_therapies",
            )
        except Exception:
            pass
        try:
            op.drop_index(
                op.f("ix_resident_therapies_resident_id"),
                table_name="resident_therapies",
            )
        except Exception:
            pass
        try:
            op.drop_index(
                op.f("ix_resident_therapies_therapy_type"),
                table_name="resident_therapies",
            )
        except Exception:
            pass

        # Finally drop the table
        op.drop_table("resident_therapies")
    # If table doesn't exist, migration is already applied (idempotent)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resident_therapies",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("resident_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("therapy_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("frequency", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("objective", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("diagnosis", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("therapist_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["resident_id"],
            ["residents.id"],
            name=op.f("resident_therapies_resident_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("resident_therapies_pkey")),
    )
    op.create_index(
        op.f("ix_resident_therapies_therapy_type"),
        "resident_therapies",
        ["therapy_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resident_therapies_resident_id"),
        "resident_therapies",
        ["resident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resident_therapies_id"),
        "resident_therapies",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resident_therapies_active"),
        "resident_therapies",
        ["active"],
        unique=False,
    )
    # ### end Alembic commands ###
