"""harden_extended_models_final

Revision ID: a8a865e8fe46
Revises: ebe4af00eb27
Create Date: 2026-02-07 14:24:02.413610

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a8a865e8fe46"
down_revision: Union[str, None] = "ebe4af00eb27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Safe drop for resident_contacts (handles index and table if they exist)
    op.execute("DROP TABLE IF EXISTS resident_contacts CASCADE")
    op.create_index(
        op.f("ix_resident_care_logs_residence_id"),
        "resident_care_logs",
        ["residence_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "resident_care_logs",
        "residences",
        ["residence_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_resident_followups_residence_id"),
        "resident_followups",
        ["residence_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "resident_followups",
        "residences",
        ["residence_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_resident_vaccinations_residence_id"),
        "resident_vaccinations",
        ["residence_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "resident_vaccinations",
        "residences",
        ["residence_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_resident_vitals_residence_id"),
        "resident_vitals",
        ["residence_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "resident_vitals",
        "residences",
        ["residence_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "resident_vitals", type_="foreignkey")
    op.drop_index(op.f("ix_resident_vitals_residence_id"), table_name="resident_vitals")
    op.drop_constraint(None, "resident_vaccinations", type_="foreignkey")
    op.drop_index(
        op.f("ix_resident_vaccinations_residence_id"),
        table_name="resident_vaccinations",
    )
    op.drop_constraint(None, "resident_followups", type_="foreignkey")
    op.drop_index(
        op.f("ix_resident_followups_residence_id"),
        table_name="resident_followups",
    )
    op.drop_constraint(None, "resident_care_logs", type_="foreignkey")
    op.drop_index(
        op.f("ix_resident_care_logs_residence_id"),
        table_name="resident_care_logs",
    )
    op.create_table(
        "resident_contacts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("resident_contacts_pkey")),
    )
    op.create_index(
        op.f("ix_resident_contacts_id"),
        "resident_contacts",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###
