"""remove_devices

Revision ID: b252ee9cd3c4
Revises: 1053bbd6ffce
Create Date: 2026-02-03 20:49:36.383531

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b252ee9cd3c4"
down_revision: Union[str, None] = "1053bbd6ffce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotent migration: Only drop if exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if "resident_devices" in inspector.get_table_names():
        try:
            op.drop_index(
                op.f("ix_resident_devices_active"),
                table_name="resident_devices",
            )
        except Exception:
            pass
        try:
            op.drop_index(
                op.f("ix_resident_devices_device_type"),
                table_name="resident_devices",
            )
        except Exception:
            pass
        try:
            op.drop_index(op.f("ix_resident_devices_id"), table_name="resident_devices")
        except Exception:
            pass
        try:
            op.drop_index(
                op.f("ix_resident_devices_resident_id"),
                table_name="resident_devices",
            )
        except Exception:
            pass
        op.drop_table("resident_devices")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resident_devices",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("resident_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("device_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("device_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "specifications",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("installation_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("deactivation_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["resident_id"],
            ["residents.id"],
            name=op.f("resident_devices_resident_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("resident_devices_pkey")),
    )
    op.create_index(
        op.f("ix_resident_devices_resident_id"),
        "resident_devices",
        ["resident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resident_devices_id"),
        "resident_devices",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resident_devices_device_type"),
        "resident_devices",
        ["device_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resident_devices_active"),
        "resident_devices",
        ["active"],
        unique=False,
    )
    # ### end Alembic commands ###
