"""add_urinary_incontinence_frequency

Revision ID: ddae3fe9e15f
Revises: e88885c5215b
Create Date: 2026-05-13 08:56:17.737262

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddae3fe9e15f"
down_revision: Union[str, None] = "e88885c5215b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "residents",
        sa.Column("urinary_incontinence_frequency", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("residents", "urinary_incontinence_frequency")
    # ### end Alembic commands ###
