"""add_specific_invasive_device_fields

Revision ID: e88885c5215b
Revises: ba5d3c37e9bd
Create Date: 2026-05-13 08:46:52.624562

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e88885c5215b"
down_revision: Union[str, None] = "ba5d3c37e9bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "residents",
        sa.Column("device_nasogastric_type", sa.String(), nullable=True),
    )
    op.add_column(
        "residents",
        sa.Column("device_nasogastric_date", sa.Date(), nullable=True),
    )
    op.add_column("residents", sa.Column("device_veis_type", sa.String(), nullable=True))
    op.add_column("residents", sa.Column("device_veis_date", sa.Date(), nullable=True))
    op.add_column(
        "residents",
        sa.Column("device_catheter_type", sa.String(), nullable=True),
    )
    op.add_column(
        "residents",
        sa.Column("device_catheter_date", sa.Date(), nullable=True),
    )
    op.add_column("residents", sa.Column("device_peg_type", sa.String(), nullable=True))
    op.add_column("residents", sa.Column("device_peg_date", sa.Date(), nullable=True))
    op.add_column(
        "residents",
        sa.Column("device_tracheostomy_type", sa.String(), nullable=True),
    )
    op.add_column(
        "residents",
        sa.Column("device_tracheostomy_date", sa.Date(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("residents", "device_tracheostomy_date")
    op.drop_column("residents", "device_tracheostomy_type")
    op.drop_column("residents", "device_peg_date")
    op.drop_column("residents", "device_peg_type")
    op.drop_column("residents", "device_catheter_date")
    op.drop_column("residents", "device_catheter_type")
    op.drop_column("residents", "device_veis_date")
    op.drop_column("residents", "device_veis_type")
    op.drop_column("residents", "device_nasogastric_date")
    op.drop_column("residents", "device_nasogastric_type")
    # ### end Alembic commands ###
